#!/usr/bin/env bash
# TIER A - laptop validation of the design's mCpG system. Generated by make_configs.py.
# Review before running. Foreground only; 6 threads; one run at a time. Estimated ~2.4 h in total.
#
# Stop safely at any time with Ctrl-C. Resume by re-running step 3 with --resume.
#   Lost work on Ctrl-C: minimisation (<= ~13 min) restarts; an equilibration stage restarts from the
#   previous stage's end (<= ~16 min); production restarts from the last 5 ps checkpoint (<= ~8 min).
#   Frames and log rows written after that checkpoint are discarded on resume.
# Planned stops: add --stop-after-stage <stage> or --stop-at-production-step <multiple of 2500>.
# Each resume restarts the barostat's step-size adaptation, so resume as rarely as practical.
set -euo pipefail
cd "$(dirname "$0")/../../../../.."  # project root
export OPENMM_CPU_THREADS=6 OMP_NUM_THREADS=6 VECLIB_MAXIMUM_THREADS=6
O=examples/mecp2_3c2i/md/output/tier_a

# 1. input (cached, checksum-verified)
.venv/bin/neurodna-fetch 3C2I --cache-dir examples/mecp2_3c2i/cache --sha256 f96ee9192eabe5eafc50ff0b161c51275ad6ad8f03a2c0d0e447f18a820ed7bf

# 2. prepare the design mCpG system (~1-2 min)
.venv/bin/neurodna-md prepare examples/mecp2_3c2i/cache/pdb/3C2I.pdb --config examples/mecp2_3c2i/md/next_stage/tier_a_laptop/preparation.json \
    --output-dir $O/prepared

# 3. minimise + 27.5 ps staged equilibration + 50 ps production (~2.2 h at 6 threads)
.venv/bin/neurodna-md run $O/prepared --protocol examples/mecp2_3c2i/md/next_stage/tier_a_laptop/protocol.json --output-dir $O/run
#    after an interruption:
#    .venv/bin/neurodna-md run $O/prepared --protocol examples/mecp2_3c2i/md/next_stage/tier_a_laptop/protocol.json --output-dir $O/run --resume

# 4. diagnostics + independent neurodna validation (~3 min)
.venv/bin/python examples/mecp2_3c2i/md/diagnose_run.py --run-dir $O/run --out $O/diagnostics

# Optional A2 - CpG build check (~15 min): derived model, preparation, minimisation only.
# .venv/bin/neurodna-md derive-unmethylated examples/mecp2_3c2i/cache/pdb/3C2I.pdb --residues B:8 C:33 \
#     --output $O/3C2I_CpG_derived.pdb
# .venv/bin/neurodna-md prepare $O/3C2I_CpG_derived.pdb --config examples/mecp2_3c2i/md/next_stage/tier_a_laptop/preparation.json --output-dir $O/prepared_cpg
# .venv/bin/neurodna-md run $O/prepared_cpg --protocol examples/mecp2_3c2i/md/next_stage/tier_a_laptop/protocol.json --output-dir $O/run_cpg \
#     --stop-after-stage minimization
