#!/usr/bin/env bash
# TIER B - modest GPU pilot. Generated by make_configs.py. NOT RUN. Review before running.
# mCpG r1 and CpG r1 are the design's development runs (same protocol and seeds);
# mCpG r2 and r3 add consistency information. Runs are independent: one per GPU in parallel is fine.
# PLATFORM=CUDA (NVIDIA) or OpenCL (e.g. the Apple M3 Max GPU). Needs: pip install -e '.[md,plot]'
set -euo pipefail
cd "$(dirname "$0")/../../../../.."  # project root
PLATFORM="${PLATFORM:-CUDA}"
R=examples/mecp2_3c2i/experiment/runs/tier_b

# inputs
neurodna-fetch 3C2I --cache-dir examples/mecp2_3c2i/cache --sha256 f96ee9192eabe5eafc50ff0b161c51275ad6ad8f03a2c0d0e447f18a820ed7bf
mkdir -p $R/inputs
neurodna-md derive-unmethylated examples/mecp2_3c2i/cache/pdb/3C2I.pdb --residues B:8 C:33 --output examples/mecp2_3c2i/experiment/runs/tier_b/inputs/3C2I_CpG_derived.pdb

# mCpG replicate 1 (= design development run)
neurodna-md prepare examples/mecp2_3c2i/cache/pdb/3C2I.pdb --config examples/mecp2_3c2i/md/next_stage/tier_b_gpu/mCpG_r1/preparation.json --output-dir $R/mCpG/r1/prepared
# step 0: GPU benchmark (0.8 ps smoke protocol; read ns_per_day in simulation.json, then decide)
neurodna-md run $R/mCpG/r1/prepared --protocol smoke --output-dir $R/mCpG/r1/benchmark --platform $PLATFORM
neurodna-md run $R/mCpG/r1/prepared --protocol examples/mecp2_3c2i/md/next_stage/tier_b_gpu/mCpG_r1/protocol.json --output-dir $R/mCpG/r1/md --platform $PLATFORM
python examples/mecp2_3c2i/md/diagnose_run.py --run-dir $R/mCpG/r1/md --out $R/mCpG/r1/diagnostics --condition mCpG
python examples/mecp2_3c2i/md/diagnose_run.py --run-dir $R/mCpG/r1/md --out $R/mCpG/r1/diagnostics_burn1ns --tables $R/mCpG/r1/md_analysis_burn1ns --condition mCpG --burn-in-ps 1000

# mCpG replicate 2
neurodna-md prepare examples/mecp2_3c2i/cache/pdb/3C2I.pdb --config examples/mecp2_3c2i/md/next_stage/tier_b_gpu/mCpG_r2/preparation.json --output-dir $R/mCpG/r2/prepared
neurodna-md run $R/mCpG/r2/prepared --protocol examples/mecp2_3c2i/md/next_stage/tier_b_gpu/mCpG_r2/protocol.json --output-dir $R/mCpG/r2/md --platform $PLATFORM
python examples/mecp2_3c2i/md/diagnose_run.py --run-dir $R/mCpG/r2/md --out $R/mCpG/r2/diagnostics --condition mCpG
python examples/mecp2_3c2i/md/diagnose_run.py --run-dir $R/mCpG/r2/md --out $R/mCpG/r2/diagnostics_burn1ns --tables $R/mCpG/r2/md_analysis_burn1ns --condition mCpG --burn-in-ps 1000

# mCpG replicate 3
neurodna-md prepare examples/mecp2_3c2i/cache/pdb/3C2I.pdb --config examples/mecp2_3c2i/md/next_stage/tier_b_gpu/mCpG_r3/preparation.json --output-dir $R/mCpG/r3/prepared
neurodna-md run $R/mCpG/r3/prepared --protocol examples/mecp2_3c2i/md/next_stage/tier_b_gpu/mCpG_r3/protocol.json --output-dir $R/mCpG/r3/md --platform $PLATFORM
python examples/mecp2_3c2i/md/diagnose_run.py --run-dir $R/mCpG/r3/md --out $R/mCpG/r3/diagnostics --condition mCpG
python examples/mecp2_3c2i/md/diagnose_run.py --run-dir $R/mCpG/r3/md --out $R/mCpG/r3/diagnostics_burn1ns --tables $R/mCpG/r3/md_analysis_burn1ns --condition mCpG --burn-in-ps 1000

# CpG replicate 1 (= design development run)
neurodna-md prepare examples/mecp2_3c2i/experiment/runs/tier_b/inputs/3C2I_CpG_derived.pdb --config examples/mecp2_3c2i/md/next_stage/tier_b_gpu/CpG_r1/preparation.json --output-dir $R/CpG/r1/prepared
neurodna-md run $R/CpG/r1/prepared --protocol examples/mecp2_3c2i/md/next_stage/tier_b_gpu/CpG_r1/protocol.json --output-dir $R/CpG/r1/md --platform $PLATFORM
python examples/mecp2_3c2i/md/diagnose_run.py --run-dir $R/CpG/r1/md --out $R/CpG/r1/diagnostics --condition CpG
python examples/mecp2_3c2i/md/diagnose_run.py --run-dir $R/CpG/r1/md --out $R/CpG/r1/diagnostics_burn1ns --tables $R/CpG/r1/md_analysis_burn1ns --condition CpG --burn-in-ps 1000
